### ISSUE TITLE
check_pgsql/check_mysql: Not supporting [-4|-6]

### ISSUE THREAD

**Issue by waja** [monitoring-plugins/monitoring-plugins#1230]
check_pgsql and check_mysql does not support an option to force IPv4/IPv6 connects via [-4|-6]. It would be very useful if this would be possible.
At least Ubuntu has for check_pgsql a wishlist bug pending: https://bugs.launchpad.net/ubuntu/+source/nagios-plugins/+bug/1061154

**Comment by RincewindsHat** [comment]
Ok, had a look at this and this would require some significant work.  I guess the steps would be (in each plugin):

 * Detect whether the `host` paramater is a DNS name or an actual (legacy) IP address (if it is, it would be useless to specify `-4` or `-6`)
 * If the parameter is a DNS name and `-4` or `-6` are given, the plugin has to do DNS resolution and pick the correct address type. If not, just stay with the current workflow.
 
I will accept patches, but do not plan to implement this myself, since I do not see a strong need for it.
