### ISSUE TITLE
check_load hardcodes path to 'uptime'

### ISSUE THREAD

**Issue by hydrapolic** [monitoring-plugins/monitoring-plugins#1394]
The path to 'uptime' binary is hardcoded when compiling monitoring-plugins. This can break the plugin:
- during compilation, put uptime to /usr/bin/uptime
- check_load works fine
- an updated 'uptime' binary can be put into /bin/uptime
- check_load fails

This was reported in Gentoo Linux:
https://bugs.gentoo.org/show_bug.cgi?id=565500

**Comment by zen2** [comment]
+1

Detection then use hardcoded path for system binaries at compilation time is a real problem.
That forces monitoring-plugins to be recompiled/reinstalled each time a binary path change as procps have done with uptime. So it have been detected on gentoo system but since it's compiled based distribution, monitoring-plugins re-installation will take care of it even if it's an annoying dependence.
But that means re-packaging and update for packages based distributions, that is really problematic.

And finally the most important: each time a system binary have a new PATH, we got no result or unknown result from monitoring probes creating unneeded alerts on monitoring systems.
Even worst, that could lead to an acceptable result (result is ok but with problems displayed on stderr) along bad performances data so you lose data without be aware of it.

**Comment by waja** [comment]
Speaking as Debian Maintainer, this is something that needs to be handled by packaging system and dependencies/breaks. I see no problem (read: compared to downsides of detecting it at runtime) with specifying a path at compile time at all.

**Comment by glensc** [comment]
i can second @waja, can be handled distribution side (versions are artificial):
- nagios-plugins 2.4-1 conflicts procps < 3.1.10)
- where procps 3.1.10 introduced path change.

probably harder to achieve in gentoo like systems, and such distros can just keep legacy symlink to minimize the breakage.

and distro should use hardcoded path from compile time to ensure idempotence
https://github.com/pld-linux/nagios-plugins/blob/auto/th/nagios-plugins-2.1.1-5/nagios-plugins.spec#L574

**Comment by hydrapolic** [comment]
@waja, what are the downsides of using execvp/execlp instead of hardcoding paths during build?

**Comment by waja** [comment]
@hydrapolic as being in up- and downstream of monitoring-plugins, in either way I want to ensure I define and detect the capabilities of external tools on compile time and have a defined environment on runtime. When using external tools that might change (in behaviour, location, what else), that can cause troubles.
When using the first binary found in path, that can be cause more trouble more easier. All this stuff should be handled by distribution toolstack.

**Comment by orlitzky** [comment]
@glensc The problem was with a new version of procps that became available to users who already had monitoring-plugins installed. When they upgraded procps (to a version that didn't exist when we packaged the plugins), the plugins broke and there was nothing we could do about it. The plugin maintainers don't also maintain procps, samba, SSH, etc. so we won't get any warning before paths change.

We can fix it in the future with "blocker" deps but it's sort of pointless. If we're going to force users to reinstall a new version of the plugins that blocks some procps -- well, the reinstall itself fixes the problem, because the plugins get rebuilt and find the correct executable paths!

@waja I can imagine a scenario where runtime detection could do something wrong, but right now, the "build-time detection" is just runtime detection... at build-time. When users install the plugins, the `./configure` picks up whatever path happens to work at the time and then hard-codes that. So if mischief can occur with the paths it could still affect a compiled-in path.

We may just have to force users to reinstall the plugins frequently (or do nothing and ignore the problem =)

I see a few other hard-coded paths for nslookup, ssh, rpcinfo, mailq, smbclient,... Monitoring-plugins would need to be recompiled every time one of those packages is updated, so it comes down to what would be most annoying in the long run. I'm leaning slightly towards "do nothing" as that is my default mode.

**Comment by glensc** [comment]
@orlitzky i understand the problem you had, in my distro it can be fixed with marking procps 3.3.10 to conflict with monitoring-plugins < 2.1.1-2, where monitoring-plugins == 2.1.1-2 is the "new" version that uses paths from 3.3.10, so users are forced to upgrade both or neither.

as for looking up programs from `PATH` security concern, there already exists `--with-trusted-path=PATH` configure option, so it should be "secure" to search them from there runtime. and i think it would also simplify whole `configure.ac` and probably cruft needed to add support for new program for use of plugin.

**Comment by RincewindsHat** [comment]
Closing this, for the purpose of tidying up a little bit. Seems to be a package system problem anyway.
