### ISSUE TITLE
check_http - make use of libcurl

### ISSUE THREAD

**Issue by riskersen** [monitoring-plugins/monitoring-plugins#1451]
On IRC we discussed the possibility of extending check_http for more authentications mechanisms.

In the end, we agreed with libcurl, which would add some benefits to check_http
- authentication protocols like NTLM, Kerberos, instead of only Basic to server and proxy
- improved proxy support
- selectable network interface for outgoing traffic
- proven HTTP interface/features
- follow redirects
- HTTPS feature like specific SSL version and encryption

and so on, please see https://curl.haxx.se/docs/features.html for details.

From my perspective, this would lead to a complete rewrite, but the benefits aren't deniable.
Of course, we could also use libcurl for the check_ftp, but this would be another topic.

Unfortunately, i don't think i'm able to work on this request, due to the lack of deeper C knowledge.

What do you think about that?

**Comment by sni** [comment]
We are in contact with the author of https://github.com/andreasbaumann/nagios-plugin-curl and will try to merge that one because its exactly what we are looking for already.

**Comment by riskersen** [comment]
These are very good news.

**Comment by ckujau** [comment]
For the record, and since it came up on [-devel](https://www.monitoring-plugins.org/archive/devel/2019-September/010423.html "feature request for the check_http Plugin") recently: the `nagios-plugin-curl` repository URL has [moved](http://git.andreasbaumann.cc/cgit/nagios-plugin-curl/ "Nagios Curl Plugin") but apparently has been incorporated as a [feature branch](https://github.com/monitoring-plugins/monitoring-plugins/tree/feature_check_curl "feature_check_curl") already.

**Comment by andreasbaumann** [comment]
Adding additional authentication methods in check_curl is on the TODO list:

https://github.com/monitoring-plugins/monitoring-plugins/blob/feature_check_curl/plugins/check_curl.c#L536

**Comment by RincewindsHat** [comment]
well, `check_curl` is there, therefore I am closing this
