### ISSUE TITLE
No release since 2016

### ISSUE THREAD

**Issue by dbk-rabel** [monitoring-plugins/monitoring-plugins#1640]
Hi,
I see that there was no release since 2016, although there have been a lot of changes afterwards. Will there be any new release? That might make it easier for package maintainers to keep there packages up-to-date.
Yours
  David

**Comment by D3luxee** [comment]
Hi,
I agree with @dbk-rabel and currently im facing issues with the version of the monitoring-plugins on debian stretch & buster which are based on the v.2.2 release tag.
The check_ping -4 command does not work properly since its using the ping command without the -4 flag.
Without the -4 flag the ping command will prefer ipv6 over ipv4 if available.

If i run the ./autogen.sh by myself on the same host:
Tag v2.2:
`--with-ping-command: /usr/bin/ping -n -U -w %d -c %d %s`
master branch:
`--with-ping-command: /usr/bin/ping -4 -n -U -w %d -c %d %s`

Now i have to maintain my own package of the monitoring-plugins just to fix this issue. In my opinion it would make sense to tag a new release in the near future to give the package maintainers the chance of updating their packages.

**Comment by waja** [comment]
Dear @D3luxee,

> I agree with @dbk-rabel and currently im facing issues with the version of the monitoring-plugins on debian stretch & buster which are based on the v.2.2 release tag.
The check_ping -4 command does not work properly since its using the ping command without the -4 flag.
Without the -4 flag the ping command will prefer ipv6 over ipv4 if available.
>
> If i run the ./autogen.sh by myself on the same host:
Tag v2.2:
--with-ping-command: /usr/bin/ping -n -U -w %d -c %d %s
master branch:
--with-ping-command: /usr/bin/ping -4 -n -U -w %d -c %d %s
>
> Now i have to maintain my own package of the monitoring-plugins just to fix this issue. In my opinion it would make sense to tag a new release in the near future to give the package maintainers the chance of updating their packages.

It would be really great to report issues in Debian. You can [check](https://wiki.debian.org/HowtoUseBTS#:~:text=If%20you%20want%20to%20report,reports%20for%20a%20given%20package.) for existing bugs and if there is none yet, please [report](https://www.debian.org/Bugs/Reporting#:~:text=You%20can%20report%20bugs%20in,for%20you%3B%20please%20use%20it!) it.

Cheers, Jan (with my debian maintainer hat on).

**Comment by ghciv6** [comment]
`It would be really great to report issues in Debian. You can check for existing bugs and if there is none yet, please report it.`

I think the package maintainer should monitor the upstream project itself. But i would also prefer a new release to distingish the code base and help package maintainer to detect the time to update.

**Comment by waja** [comment]
Dear @ghciv6 

> I think the package maintainer should monitor the upstream project itself. But i would also prefer a new release to distingish the code base and help package maintainer to detect the time to update.

as you may know, Debian is a voluntary project. The documented way of the Debian project to report bugs is inside the BTS. Please keep in mind, that mostly packages are team maintained and even those are in most cases lacking manpower. You can expect what ever you want, also that maintainers monitor their upstream projects (what they mostly do in one or another way), but you should make their life not harder, so please do them a favour and report bugs where it is expected. Especially as @D3luxee described a packaging issue.

Jan, Debian maintainer of monitoring-plugins package.

**Comment by ghciv6** [comment]
Dear @waja 

it's clear to report a packaging issue to the package maintainer.

my intent was:
the debian package is only one package related to this project. the best signal to all of them is to increase the version number on a regular base.

**Comment by Al2Klimov** [comment]
> Now i have to maintain my own package of the monitoring-plugins just to fix this issue. In my opinion it would make sense to tag a new release in the near future to give the package maintainers the chance of updating their packages.

I have the same problem with #1614.

**Comment by hydrapolic** [comment]
Same for Gentoo Linux, I'll gladly add a new version when the tag is available.

**Comment by sni** [comment]
Fixed in #1651. Thanks for your patience.
