### ISSUE TITLE
check_by_ssh: Add option for host key trust on first use

### ISSUE THREAD

**Issue by NexAdn** [monitoring-plugins/monitoring-plugins#1825]
Currently, check_by_ssh fails if the host key for the host to check is unknown. When adding new hosts to the monitoring configuration, this creates the problem that the host key for the IP addresses must be added manually before the checks can succeed or host key checking must be disabled completely.

A nice addition to check_by_ssh would be some kind of trust-on-first-use option, which automatically adds the discovered host key if there is no known host key for the host that is to be checked.
This could make configuring monitoring for new hosts completely automatic without any additional scripts that scan the SSH keys.

**Comment by RincewindsHat** [comment]
Hey @NexAdn, firstly thanks for the idea. I will be honest, I am kinda hesistant to do this, since TOFU has the implicit assumption, that first contact was established before anything bad happened and IMHO sabotages the whole "chain of trust" thing.
Ideally people would really use SSH certificates on their machines, but at this point in time I have only seen that in one single setup.
But then again it is unlikely, that an attacker managed to MITM the connection before first contact and well, people use SSH that way anyway in most of the cases, so it might at least be less effort.

I am little bit torn whether this should be implemented. @waja, @sni  Any opinions?

**Comment by NexAdn** [comment]
First of all, thank you for considering this issue!

> I am kinda hesistant to do this, since TOFU has the implicit assumption, that first contact was established before anything bad happened and IMHO sabotages the whole "chain of trust" thing.

That is a valid concern. However, we are talking about a login that is likely highly restricted here and a connection that is maybe limited to a management VLAN (or similar), so getting to a point that an attacker might do an MITM attack is very unlikely. Also, from my experience (and it seems that you have experienced this as well) most sysadmins don't care to check the host key before connecting with their root-enabled logins.

I would definitely disable such a behavior by default and only enable it with a command-line option. This should never be the default behavior. Having a TOFU option is still much more secure than going the completely lazy way of disabling host key checking altogether.

**Comment by sni** [comment]
I don't think it's necessary and i don't think it's a good idea. You either setup new hosts manually, then it's one small extra step. Or you provision new hosts automatically, then it's
just a simple extra step to roll out keys.
Or you don't care about host keys anyway and disable all host key checks.

**Comment by RincewindsHat** [comment]
So, coming back to this and regarding @sni perspective on this, I think we are not going to do this, which is nice, because it's less code :-) .

Sorry to disappoint you, @NexAdn.
