### ISSUE TITLE
check_disk: Performance data should also contain disk usage in percent

### ISSUE THREAD

**Issue by lgmu** [monitoring-plugins/monitoring-plugins#1981]
Hi,

currently, even when using % thresholds, the perf data will only be returned in Bytes.

I like the Nsclient approach on check_drivesize:
'C:\ used'=74.482GB;94.67343387566507;94.67343387566507;0.000;99.656 'C:\ used %'=75.000%;95;95;0.000;100.000

I think it would be helpful, especially when building grafana dashboards using the pnp datasource, to additionally have the percent values as performance data.

So for example:
/dev=0B;1772303155;1870764441;0;1969225728
'/dev free %'=100%;90;95;0;100

Or to avoid spaces and % in the name:
'/dev_free_pct'=100%;90;95;0;100

Personally I'd prefer used % over free %, but that's probably a matter of opinion.

**Comment by RincewindsHat** [comment]
Hi @lgmu,
I think I argued against this in the past, since the data would be redundant. This information is already there and computing percentage values should be something the monitoring system or the performance data visualizer would do.

Adding the percentage values to the to the performance data would increase the storage it takes up by a factor of two, since I haven't yet seen a system to filter out specific values.

But, for convenience, I would be open to adding commandline switch to additionaly display the percentage data.

**Comment by RincewindsHat** [comment]
I am closing this issue, but would be still open for PRs to add that parameter
